# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddf4d6cd9701a6cc22f274d11f960cbfb34d334c757b559722ba5cf8e162f141d36cb814fa9d6c8d20f788ffce74e8380b9f8cbee45ff449e29a48a9e1a0068e

test:
  secret_key_base: 2f715a01d455b61c8570880d6e25445712bbc517d66aff8c01e4cb51d52c40a713bc101f9aff77457f2514aea36cdae9c9afb09c58c8ccbfae137f882211fde3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
